apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: infra
  labels:
    app: alloy
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: promtail
      volumes:
        - name: alloy-config
          configMap:
            name: alloy-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/log/containers
        - name: docker-containers
          hostPath:
            path: /var/lib/docker/containers
      containers:
        - name: alloy
          image: grafana/alloy:v1.12.0
          args: ["run", "/etc/alloy/alloy.yaml"]
          volumeMounts:
            - name: alloy-config
              mountPath: /etc/alloy
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/log/containers
              readOnly: true
            - name: docker-containers
              mountPath: /var/lib/docker/containers
              readOnly: true
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
