apiVersion: v1
kind: Secret
metadata:
  name: auth-jwt-keys
  namespace: auth
type: Opaque
stringData:
  private.pem: |
    -----BEGIN ENCRYPTED PRIVATE KEY-----
    MIIJtTBfBgkqhkiG9w0BBQ0wUjAxBgkqhkiG9w0BBQwwJAQQIf4F1u3D7JiB9MrM
    mB/0BAICCAAwDAYIKoZIhvcNAgkFADAdBglghkgBZQMEASoEEJTJVjDUbVDFkOHx
    qVVFj3sEgglQGBS3euDuhORRrUmfjAwAsUFVY3SoyT9VXZZYmI34wtdyVBJRsN6w
    ADPtDfx1Z2lb7QFPGjEfRPcx+wpp64QOzw0HLa08QswWukWtIVobzWC5r/1pXXbP
    qvBJY1/9PztfScGJfM9d9by9G8RwBTcer42tU5BwDbitbUZzyHOLEbMS+pQfB/Qu
    IKasxSGqxTK7RsloYMoRebsb3fw7qzEs0P0wjAwmIFci4DNJfzMGXtmTUS3RpS9X
    jeqi0qeJLTE3d1lUSdp+CeLxyu/cY+Hq/PWfwXU3zE7RTHRvkB/5YwHW2yH0Rt1R
    JnEqMx40Bpx0e2YrOk3ni4n93CVNtsI3xq0DcxF/QVCCpUl0tSNDIt9MPkhVhpWE
    lQHF47/5h4j6AE4vrrTiXaZR3BNNw29zJImXn1IOFND7ZzTWulnXJ3eoY7kpZsJP
    4iFWoBVMQgBLgdabFZmK58rmLzOC8ePQyw/VjMCPTN4xYnmfEwCrSR8Ta8BPh7py
    3Pp8L6kJFfRl0nNGsKAcWvlN6GKhTzhN39SsGqo7eLkSJQRFRSRRA0bhbwNRbwDR
    JeObiIlRD0swyeSPKzxGN+AyTu8aGRsnh7Kook3ctNFrG90wz/y6bZu1bDxlu9Uf
    zSzmi3cG6wHM0313kRKbtMJL4Q7Aspq0YSugXOAuTkwZQJ2JpZx/DGPfYOWtx6z7
    cHA98rNDFy6Iw3pTW7i/Wzqte5cboe40GMn2GUs2ElNZHvUvX3vT3cC8F0YHX+//
    WC23wSlRPleRc3jhxtx25y+N7t6BodNueBOedd2nmcozHKYN2b2qQZXiQ0s0zLcP
    FuH/VJ2i7f7PiF4TedkJkJjlKiY53kCDUAs/R60ipT3Vr3MWTweTA3JMt6z2oyqN
    wvze9ZC2LqzJAsLa9YlQDp9nS5Ew0CaQts28qX7JVfDqODWC1sqdmxCAw2gUXwwF
    fTYqmJFcxiFtQr4rTQOCITMzHZkECPFnRgycPD7iJh9AfEcS9s7aKPdCt17eiLfn
    IVC8ZFRscduNvg5A8Q9LGQas/ITU7K0Q9osjkXS28LjOzu7K8dDMp6UnkJkxwnIQ
    cEc8SiJbn0lQ1NmSXnBShyIeHrSqh57cvCH+ZK2UEusc1t2em3n5avdkLvqNfzrX
    GSNrG6HJ34UZtsa2rHb5rGNVhyq9yeBZ3oArSB8KgRXaStgBQR9DyWUMAvC2toVc
    bgQyHiJLjrKVxXygyo0RTWQyZANfcesH0ridmsq+qJaCToHV/mOTFymBC/Oio4a+
    5NdfG1DcejSsTkfRZgbkCpblXvf63R7ynR5iYfs9R2ewgL63OcR0PKSo8YH+CNdU
    xpN8GLy5y+Lh4ysbUgpmRpjSedyzqVfAk017Whz68UewnHcw2M4cRbjMsIFIS7ER
    UKttZOpk+zVG9YwlnhbvwEfyOfsIkkOaXlC6M3ihpqA6UOhBt8q0eeXl5dF+Qq0m
    Rfp90uLh+cNnIG2aIOHeDZeOlXpLLdFhpAzKnCVxDCCSdZWGYVzBTfEU6QuYxJFq
    7eFHNQOruAoHJ0rAqdMCbKRKkB0ZsrJDchxCJZ5Jah9qF7o4vFHRBG/o/dJHuUcJ
    Lj44HOdymA0BL3hWM+sdkZL5pZieadjU/iZP1ulXoRUoM0qptnAmkuFlSXT27JWd
    lawIUnJ5fN0gzes8SqR0CXafBQ1KMN6jnR2Ly4oRI1Eos+lBBLYGXRkU3uBjcDkv
    lm4ruIQZFAtkVPJn2bcurG9zbXMpnr+Z5TLjUldG4ptSDF3ZJkI2u3mk2DyplB99
    TPyeV/f9NFuY1eDq9AIRxddTnbrNTSNSNqnyP06kzS1tputkgml2laMXZ649hZrV
    hwYcw3JTpMwyGYpnJ3vip7UNP2SPu8T6yWDV8FQadCIoJ6r8ITF6WPMVcH2M+9rc
    3BnE+cJ0sxkeKFLAH1/fyDUm6vrqsMPTWmQ6rIoNFVN2lHdgIMzesEKSbmwqZj4M
    e/ZpuCnoyPSAFtYxbzdTFnadMul8JlqKm2VTbVJ442Rgs2ZSNJgnhVkyHiDmVaib
    SKmKMOgrO6kPlQ4nAunv71KwzwxrLfGdmpkFoi1uvYRUt2dghQevzZVBEvjrzOMm
    4nVVc0llAm6BgTjaq00WYZeEKB6ciEpUwtti0ZasjuToL+DPwFWyIivypRyWzmXA
    e97cw0CPKWg5yr7F7kV1g0tbYd8sG+9sZ3/t3tC5iOg0/B8qiL6+EEu4JGVeCF/l
    jAnpSIy1fgUwwJogw8NDjKz+UH0AgJ3dHwT4sNaAijKKlf38ypXqBY+F1RJZnAq0
    DLZ4GaXzrmx9cehz8/12PLjElQ2wb+jk/UHE8Ms4yAiZXBYYjQptPohQUF3+TBAs
    22WDjAO1oR2/llzBBlTIfJmWDy8/B9I1J0DHoVjvNxTfC5HKNQfk9c/MgQJdrBWw
    BTVzcVvuZ6HgoLSiWFDKF89u+kBjU8+R3t3dh13IhmcWT0b3UqlHjN5FshjnFqTo
    i+dCXfnIirWLwcpsIUznlrNwF+OFxiGeSZdd6Mhak50kdjhy9oOHOAOS1ue3Lktz
    CL56QvAER0aZhLVTo+w4FbcUZeMB5oHG4aokuks2Z3ZPWdmGWcVfPtuRj9wPwS0V
    35FDOgDWbe9i0CJtuAC9jORdYL0A300o4iszOQ+H6Og4N4TmbPFPSlyUAUgupLdC
    K6MhMSk18cjJF1y4Dub/FI0hAH7eZZnjcraPXPhGf4HsIRxmycKgB4DLUgbJJpUA
    wWe5aPDUoLidHm+XyiSDgrkjSoFJWf8XVWxdG83xboWE/gwq8a5M+KPKF2x4Umbu
    SHSyAj3FMZ8D8xp5MzGQPYfbegwV3lTjuScnMwgDRfTt/efwXPwYpwilZDZLjKBb
    Py6KRwWeq5R4Bn1ghY/3QoJenT8OLZOLhTV6X1/Y8EuZQStaVu7Ta8nz1FgSmPMR
    WMoSlnPeNnJ1QpHy4tM8nfu7D2fNxJLM1tjNH6Ul/Am427tdQ3ioe0s34UjRXjZl
    yFgbvIn1jlR6cuZfrqpRI/hnr1AJ9uIwcIAiKoXzdKAY/jQV2wClOXLqkIaGcv61
    wszbICpC+gsP4xXfcDISs3Nf+qRnYSXOUsbLCbSyh5j6BYmP2Is7rqJ+bw4+EXFz
    T8ngGr2oTo3HkZnCgWS3QZMTj0Gms3m0nNj3y0TF+7isXdtVGs2xN4Q=
    -----END ENCRYPTED PRIVATE KEY-----
  public.pem: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwq6hRsM1FaYTlN+ehbHU
    HfQOdrhwR7kSw43z6QFinN2AJixXIc7VI9APe0pYVBuA/xUmBaQn3PwfVil8NjMl
    ZApI4XvcD3vr3/Xqw3sU1ME3nPoLVXIFGZ3Fqv+YpYQCVkEf8zDi/e9KHkmn9kFd
    uw4IWO0TNVKcGoat42hvYM1T4f2d8ZQr0DQB+QBnDTaaYmMdoNxbsqbfcAwCjABN
    v14wRHF21HFhzEtPM4OoIE452HeSHKxrBt+7FXvSAxKlCtOsdtKWravk57EeZYHG
    Ue6+rdd2+SLJH+yApucpFPB8wII14/7WEOAxqhw0ZORCWLb1dLT9ruaCFruT7kwT
    aRc+Z/u3DTHMyI4OfPVmLx2J4kkg/cyGfxdX6yKyLWt9aRkO2Q1LkbtCK//liIsq
    LLz7rkyP8rsTA4j1KMArWh9tMISfdpAX1uQBmrU3NqhqCnlc4v1x4kWtmo6Z1uOe
    3Zzyy1QV7yyP+LRsxWJ4VbkCxU1EKRy3qx+RpUTaOS6mr5DezJSRBgmhMJrGYdai
    5lr1aBz6cc18vWr4WKJu7kFC0UOISbpid/zdrzDxBQnU/QpTqNhJcmdRUNqtXRlu
    f3nFJGj7kUIgN323bgAZPWBG0PEUB+gYSaMhYg4ELTZ87F2RLZtuJj5+KcT9YtmG
    YLGCKWO9zr47n0EMDySO4JECAwEAAQ==
    -----END PUBLIC KEY-----

